version: "3.7"

networks:
    transfer-net:

services:
  transfer:
    image: dutchcoders/transfer.sh:latest
    container_name: transfer
    command: --provider local --basedir /opt/transfer/ 
    ports:
      - 8080:8080
    networks:
      - transfer-net
    volumes:
      - /opt/transfer:/tmp
    restart: always

